### ISSUE TITLE
Suggestion (a bruit force solution for sys-ftpd issues

### ISSUE THREAD

**Issue by fennectech** [StevenMattera/SDFilesUpdater#17]
If sys-ftpd causes corruption only sometimes (wich is definitly true)   cant we hash the file that we just wrote and compair it to the one in the zip   and if they dont match   write again    and again  until we get a good write?  Itd increase how long it takes   but it would make it possable to use it with sys-ftpd

**Comment by StevenMattera** [comment]
The problem isn't with writing the file, it's specifically the file allocation table.

```
The bug is in Nintendo's exfat driver. It constantly changes folders/files even on reads. And because it never syncs properly, on a hang/force quit/force reboot/power off, the handles are lost and the files/folders become missing from the file allocation table. Because exFAT does not have a 2nd FAT like fat32, these file/folders cannot be recovered.
```
