### ISSUE TITLE
Progress bar and background picture

### ISSUE THREAD

**Issue by 2g4y1** [StevenMattera/SDFilesUpdater#3]
Is it possible to create a background picture and a download progress bar?
Would be nice =)

**Comment by StevenMattera** [comment]
I have a branch I've been working on that includes a graphical user interface, but have been on a break (for this project at least) for the past few month. Now that my Switch is hardware modded it makes it much easier to debug crashes that forces my Switch to restart. Not going to make any promises, but should have some progress on this shortly. In the mean time attached are some mock ups.

![01-downloadingpackagelist](https://user-images.githubusercontent.com/697668/46219448-6883d580-c315-11e8-99e9-b5c97f6591f6.png)
![02-updatetosdfilesupdater](https://user-images.githubusercontent.com/697668/46219449-6883d580-c315-11e8-810b-07754a605b39.png)

**Comment by StevenMattera** [comment]
SDFiles Updater 2.0.0 is now live.
